### PR TITLE
update training center url in toc.yml

### PR DESCRIPTION
**Pull request by lemonez**

### CODE REVIEW

**Comment by lemonez** [comment]
goes w/ #434

**Comment by stevielkim** [comment]
Since there is no dev advocacy group, just ping me to review

**Comment by lemonez** [comment]
@StephanieKim Nathan added me to a new group called dev-advocacy in order to allow me codeowner access (wasn't sure what existing group I should be part of so we made a new one). That is why that group is selected for review. Let me/Nathan know if there is a better workflow here. But the goal was to enable me to merge PRs here.

**Comment by bnlb** [comment]
> @StephanieKim Nathan added me to a new group called dev-advocacy in order to allow me codeowner access (wasn't sure what existing group I should be part of so we made a new one). That is why that group is selected for review. Let me/Nathan know if there is a better workflow here. But the goal was to enable me to merge PRs here.

Since the vast majority of Ezra's changes are markdown updates I didn't want either of you to be blocked waiting for UX to review something if it's just copy related. That said, we're always happy to review if you'd like more eyes on something.

**Review by bnlb — APPROVED** [review]

**Pull request merged**
