### PR TITLE
UXENG-2214 Update documentation for webhook modal

### PR DESCRIPTION
**Pull request by bnlb**
Resolves the dev-center side of [UXENG-2214](https://algorithmia.atlassian.net/browse/UXENG-2214)

### CODE REVIEW

**Comment by ryanmillerdev** [comment]
One thing to make sure of is that our screenshots don't actually contain any live, complete credentials. Thinking we should fuzz out the greater portion of the webhooks secret and deploy key?

**Review by ryanmillerdev — COMMENTED** [review]
Made a note about the credentials in screenshots, and also thinking our screenshots should better highlight the area we want our users to see. Your screenshots were taken on a high-res screen so it's a bit hard to read the text and figure out what should be clicked.

**Comment by bnlb** [comment]
> One thing to make sure of is that our screenshots don't actually contain any live, complete credentials. Thinking we should fuzz out the greater portion of the webhooks secret and deploy key?

I should've added a comment to my description. I plan on deleting the algos/repos referenced in these screenshots since I'm not using them for anything. Just created for the sake of testing the UI as I created it. I'll delete those now.

**Comment by bnlb** [comment]
I've cropped the images to remove some extra space and deleted my test algorithms/repos.

**Review by ryanmillerdev — APPROVED** [review]

**Pull request merged**
