### PR TITLE
create arthur.md

### PR DESCRIPTION
**Pull request by lemonez**
to satisfy requirements set out in: DOCS-141

### CODE REVIEW

**Comment by lemonez** [comment]
@StephanieKim please review

**Review by stevielkim — CHANGES_REQUESTED** [review]
Awesome, thanks, this is great, the only thing that I would like you to add is at the bottom of the page, add a closing sentence or two, pointing users to our advanced usage reporting doc, and insights doc with brief descriptions about those two features and a link to contact sales if they are new to algorithmic (not sure where that makes sense, I'll let you decide)

**Review by stevielkim — APPROVED** [review]
You rock perfect thanks!

**Review by bnlb — APPROVED** [review]
LGTM!

Can you check if you're able to merge yourself now that the codeowners update landed?

**Comment by lemonez** [comment]
@bnlb I still don't seem to have the ability to merge :/  is there some specific config option that needs to be changed to give write access?

**Comment by bnlb** [comment]
> @bnlb I still don't seem to have the ability to merge :/ is there some specific config option that needs to be changed to give write access?

I'm not sure why this isn't working. I've added the @algorithmiaio/dev-advocacy team to the codeowners file on the develop branch. I found a GitHub issue where someone had a similar problem and fixed it by giving write permissions to the team itself (instead of all members), and even after doing that it's still not showing the dev-advocacy group as a codeowner when I open a dummy PR.

I'll keep looking into this, for now I'll just merge these PRs for you as they get approved.

**Comment by lemonez** [comment]
Ok sounds good, thank you!

**Pull request merged**
