### PR TITLE
Integrate New API Docs

### PR DESCRIPTION
**Pull request by ryanmillerdev**
In order for our [updated API documentation](https://github.com/algorithmiaio/api-docs/pulls) to be complete, we need to document our admin API keys. This PR introduces a new snippet at the end of our [API keys documentation](https://algorithmia.com/developers/platform/customizing-api-keys).

### CODE REVIEW

**Review by bnlb — APPROVED** [review]
🗝️

**Comment by bnlb** [comment]
I'll hold off on cutting the release until this is merged.

**Comment by ryanmillerdev** [comment]
@bnlb You can go ahead and cut–I'm actually going to merge this + the API docs branch simultaneously since the old API docs don't actually discuss any admin endpoints.

**Review by eliperelman — APPROVED** [review]
LGTM!

**Pull request merged**
