### PR TITLE
Add environment matrix page

### PR DESCRIPTION
**Pull request by danielfrg**
Adding a page describing the different environments dependencies

### CODE REVIEW

**Review by bnlb — CHANGES_REQUESTED** [review]
Seeing some issues with the rendering of the table:

Screen Shot 2020-11-20 at 4 45 30 PM

Once that's updated this is good to ship. 🌟

**Comment by danielfrg** [comment]
I am kinda confused where those issues are coming, i tried rendering it on vscode and it works fine. That html code before the table is not in the .md file.

I will try to setup a dev environments for this repo to check this out

**Comment by aslisabanci** [comment]
Hey @danielfrg - just came here to chime in with my 2 cents :) yep setting up your local environment to run this with jekyll by  `npm run devcenter:public`, etc. on your machine and rendering it in your browser would be helpful to see how it would look like in the end - at least it was for me. There are also some dynamic macros in some other pages and when you're about to do something with those, you'll benefit from this setup too. You may run into issues with those ruby gems while setting this up and it might take some time but the investment is worth it :)

**Comment by danielfrg** [comment]
Ok, i changed the table to an MD table so it should fix the html issues.

**Comment by bnlb** [comment]
Thanks for the quick update @danielfrg! I just pushed a small update that wraps the table in some of our UX utility classes for better readability. All set to merge whenever you'd like.

**Review by bnlb — APPROVED** [review]
👍

**Comment by danielfrg** [comment]
Thanks for the fix!

**Pull request merged**
