### PR TITLE
Frontend 1871

### PR DESCRIPTION
**Pull request by bnlb**
Resolves [FRONTEND-1871](https://algorithmia.atlassian.net/browse/FRONTEND-1871)

### CODE REVIEW

**Comment by langlk** [comment]
Are there any env variables that need to be set for this to take effect? I'm not seeing changes show up when I tweak the UI

**Comment by bnlb** [comment]
Ah, my bad. When I wired this up I was doing a combination of pointing the API request to prod and hardcoding the hex value for the side nav. I've updated config values in test so that you won't be able to miss the updates.

You'll see updates for the site title, the brand title, and the nav come through. (The logo was already wired up to use `/v1/config/logo` so I didn't have to change that.)

Screen Shot 2019-11-19 at 8 51 12 AM

**Comment by langlk** [comment]
Huh, it looks like `npm run localdevcenter` still isn't working correctly then, because I was checking using that and it wasn't working.

**Comment by bnlb** [comment]
> Huh, it looks like `npm run localdevcenter` still isn't working correctly then, because I was checking using that and it wasn't working.

I'll investigate.

**Pull request merged**
