### PR TITLE
UXENG-3589

### PR DESCRIPTION
**Pull request by cannedyeti**
[UXENG-3589](https://algorithmia.atlassian.net/browse/UXENG-3589) - Attempting change from slate to redoc.

## Checklist
- [ ] My PR title includes a relevant Jira ticket name
- [ ] If no associated Jira ticket, my PR title is informative (individual commit messages are squashed in this repo)
- [ ] Unnecessary text (notes, TODOs, etc.) has been removed
- [ ] For YAML "front matter":
  - Properties are alphabetized
  - `permalink` and `redirect_from/to` properties have `/` at beginning and end (e.g., `/path/`)
- [ ] Screenshots, if present, follow the [Screenshot guidelines](https://algorithmia.atlassian.net/wiki/spaces/CUSTOMERS/pages/1634861478/CFD+Style+Guide#Screenshots) which means:
  - Full browser width (browser at 100% zoom and 10-12" width)
  - Max 1000px
- [ ] Grammar, style, tone, punctuation, etc. follow the Algorithmia [manual of style](https://docs.google.com/document/d/1PPVfgMkX7-EVGLPMhN1E485CAXu9QfhSLKM0lZhnZdU/edit?usp=sharing)
- [ ] Headers are “Sentence case with Proper Nouns capitalized”
- [ ] Placeholder strings are `UPPER_SNAKE_CASE` and are named as in the [Glossary](https://algorithmia.com/developers/glossary) where appropriate

### CODE REVIEW

**Comment by lemonez** [comment]
🥁

**Comment by lemonez** [comment]
@cannedyeti I've added code samples to the spec in the `algorithmia` repo and I've added release notes here. Please review the latter and then I say let's merge this sucker. Do you know what version this will go in so we can update the version number in the release notes?

**Comment by cannedyeti** [comment]
> @cannedyeti I've added code samples to the spec in the `algorithmia` repo and I've added release notes here. Please review the latter and then I say let's merge this sucker. Do you know what version this will go in so we can update the version number in the release notes?

If we get this merged in today, I think we should be able to get it into the next release. 21.1.13?
All looks well on my end. 

Also opened a [ticket to improve](https://algorithmia.atlassian.net/browse/UXENG-3675) the local openapispec so you don't need to push changes to two places everytime.

**Review by lemonez — COMMENTED** [review]
👍🏼

**Pull request merged**
