### PR TITLE
add clarity in several places, naming consistency

### PR DESCRIPTION
**Pull request by lemonez**
My markdown auto-formatter hit this so it looks more extensive than it is

-Updated the GitHub part
-Clarified some things I thought were confusing re: whether it was talking about config on the Algorithmia side or the SCM provider side
-Added some links
-Made terminology more consistent
-Sentence-cased headers as recommended in the style guide

### CODE REVIEW

**Comment by lemonez** [comment]
also, planning on refactoring this into individual pages for each SCM provider, once I restructure the nav bar to accommodate that

**Review by warmbowski — DISMISSED** [review]
Rendered great. gosh, I wish my gitlab username wasn't in there. Not a big deal, but when you refactor, maybe we can alter the images a bit to obfuscate?

**Comment by bnlb** [comment]
What markdown auto formatter are you using? I've got one too and it'd be nice for us to all use the same one. Wondering if there's a way we could add a `.vscode/*` folder to this project so we all use the same settings.

**Comment by lemonez** [comment]
Was just thinking about this last night when I saw how many changes it created, so that sounds like a great idea to me. I think it's the Prettier extension that is doing the work. So adding a `.vscode/*` folder would probably be a good way to enforce this. Currently I have:
`  "editor.defaultFormatter": "esbenp.prettier-vscode",`

**Comment by lemonez** [comment]
forgot to change some file names so that they get refreshed in the CDN. will reopen after doing that.

**Pull request closed without merging**
