### PR TITLE
DOCS-324: docs for model versioning manifest file

### PR DESCRIPTION
**Pull request by lemonez**
[DOCS-324](https://algorithmia.atlassian.net/browse/DOCS-324) - guide for using manifest file for model versioning

Additional context/notes if appropriate (e.g., specifics about what's changing, links to epic or other PRs, etc.)

## Checklist
- [x] My PR title includes a relevant Jira ticket name
- [ ] If no associated Jira ticket, my PR title is informative (individual commit messages are squashed in this repo)
- [x] Unnecessary text (notes, TODOs, etc.) has been removed
- [x] For YAML "front matter":
  - Properties are alphabetized
  - `permalink` and `redirect_from/to` properties have `/` at beginning and end (e.g., `/path/`)
- [x] Screenshots, if present, follow the [Screenshot guidelines](https://algorithmia.atlassian.net/wiki/spaces/CUSTOMERS/pages/1634861478/CFD+Style+Guide#Screenshots) which means:
  - Full browser width (browser at 100% zoom and 10-12" width)
  - Max 1000px
- [x] Grammar, style, tone, punctuation, etc. follow the Algorithmia [manual of style](https://docs.google.com/document/d/1PPVfgMkX7-EVGLPMhN1E485CAXu9QfhSLKM0lZhnZdU/edit?usp=sharing)
- [x] Headers are “Sentence case with Proper Nouns capitalized”
- [x] Placeholder strings are `UPPER_SNAKE_CASE` and are named as in the [Glossary](https://algorithmia.com/developers/glossary) where appropriate

### CODE REVIEW

**Review by zeryx — APPROVED** [review]
LGTM direct lift into docs

**Comment by lemonez** [comment]
@zeryx Not exactly a direct lift; I did actually change a fair bit of text, hopefully didn't change the meaning, but please do give a quick read through to make sure.

**Comment by lemonez** [comment]
@cannedyeti when you get a chance, quick look at this from a "don't break things" perspective, thanks. I'm comfortable with the content.

**Review by cannedyeti — APPROVED** [review]
Looking fine to me!

**Review by rembrandtreyes — APPROVED** [review]

**Comment by lemonez** [comment]
thanks gents!

**Pull request merged**
