### PR TITLE
DOCS-262 Update event flows

### PR DESCRIPTION
**Pull request by lemonez**
[DOCS-262](https://algorithmia.atlassian.net/browse/DOCS-262) - update Event Flows / message broker docs

overhaul of structure of message broker docs
updated/rewrote lots of things
updated screenshots
added template code instead of saying "contact us"
also some miscellaneous commits to other files as a result of working on the Event Flows docs

## Checklist
- [x] My PR title includes a relevant Jira ticket name
- [ ] If no associated Jira ticket, my PR title is informative (individual commit messages are squashed in this repo)
- [x] Unnecessary text (notes, TODOs, etc.) has been removed
- [x] For YAML "front matter":
  - Properties are alphabetized
  - `permalink` and `redirect_from/to` properties have `/` at beginning and end (e.g., `/path/`)
- [x] Screenshots, if present, follow the [Screenshot guidelines](https://algorithmia.atlassian.net/wiki/spaces/CUSTOMERS/pages/1634861478/CFD+Style+Guide#Screenshots) which means:
  - Full browser width (browser at 100% zoom and 10-12" width)
  - Max 1000px
- [x] Grammar, style, tone, punctuation, etc. follow the Algorithmia [manual of style](https://docs.google.com/document/d/1PPVfgMkX7-EVGLPMhN1E485CAXu9QfhSLKM0lZhnZdU/edit?usp=sharing)
- [x] Headers are “Sentence case with Proper Nouns capitalized”
- [x] Placeholder strings are `UPPER_SNAKE_CASE` and are named as in the [Glossary](https://algorithmia.com/developers/glossary) where appropriate

### CODE REVIEW

**Comment by warmbowski** [comment]
The only things I can think of on the highlighting of platform when on platform-administration is that maybe the redirect property effects the highlighting. I can't figure out any thing else. when I look in the _site folder (local dev build), I see three folders generated. platform, platform-admin, and platform-administration. I just wonder if that's because of redirects and stuff. Bottom line, I can't figure it out, but I bet there is some clarity in the Jekyll docs on that.

**Comment by warmbowski** [comment]
Oh, I just noticed that when clicking on Platform Features, or Platform Administration, they are rendering the exact same page. Maybe that is why they both highlight when either one of those menu items are clicked on. So my guess is that it is something in the platform.md and platform-administration.md

**Review by warmbowski — APPROVED** [review]
lgtm

**Comment by warmbowski** [comment]
You should get this in asap and fix the platform/platform administration thing later.

**Comment by lemonez** [comment]
Thanks. I have gone line-by-line through those two files and tried all sorts of different things with the front matter and it didn't seem to be the issue, but the fact that it's still creating a "platform" folder in the _site folder is suspicious, so I think that's probably a good place to start. Merged this and I will look into that next.

**Comment by lemonez** [comment]
I deleted some stuff to get rid of the `_site/platform-admin` folder as well as `_site/admin`, which shouldn't be there. Beyond that, yeah something wonky is going on with the redirect links. I've spent too much time on it and it's been fruitless so just going to leave for now since it's functional, and hope we migrate this stuff at some point anyway :)

**Pull request merged**
