### PR TITLE
minor typos and suggestions in python client docs

### PR DESCRIPTION
**Pull request by lemonez**
note that the following changes are per PEP-8 style guidelines:

    `if not img_directory.exists():` instead of `if img_directory.exists() is False:`
    `if not client.file(img_file).exists()` instead of `if client.file(img_file).exists() is False`
    `if client.file(download_uri).exists():` instead of `if client.file(download_uri).exists() is True:`

Also to note: in its current state, the algoCV algorithm ('dlib/FaceDetection') does not accept a `pixels` value in the input; maybe this was part of a previous version of the algorithm, in which case that version needs to be pinned by adding the version number to the `client.algo()` call. Also, I do not currently get an 'output' key in the response object, only a `url` key; maybe that was also part of the previous algorithm version.

### CODE REVIEW

**Review by bnlb — APPROVED** [review]
Thanks for all the spelling fixes. I'll get this deployed with our next marketplace deploy. ⭐

**Comment by koverholt** [comment]
I came across a couple of other typos in code examples that I thought I would include in a comment in this PR rather than opening a new issue or PR.

`print(reponse.result)` should be `print(response.result)` in a couple of places:

* https://github.com/algorithmiaio/dev-center/blame/230e9e6a635c3402e1c12bf3392bfcccc27b6fe6/_pages/clients/python.md#L78

* https://github.com/algorithmiaio/dev-center/blame/230e9e6a635c3402e1c12bf3392bfcccc27b6fe6/_pages/clients/python.md#L98

**Comment by noahcrowley** [comment]
Fixed the two typos @koverholt pointed out, hope that is OK @lemonez, I committed to your fork.

**Review by lemonez — COMMENTED** [review]
Looks good, nice catch!

**Pull request merged**
