### PR TITLE
Remove "robots: none" from all docs pages

### PR DESCRIPTION
**Pull request by kennydaniel**
For some reason, a huge number of pages in the docs were marked "robots: none". This results in a robots none meta tag being added to those pages, which prevents indexing by search engines. This can be verified by trying (unsuccessfully) to find those pages using google.

This PR fixes this on all pages. Docs might be the MOST important thing to be google-able.

### CODE REVIEW

**Review by stevielkim — COMMENTED** [review]
Actually this looks like it was not a copy and paste error, but was added after the fact, can we confirm from @cannedyeti who looks like he's worked on related code in Dev Center or @eliperelman why this change was made or who made it?

**Comment by eliperelman** [comment]
This was done as part of [GROWTH-738](https://algorithmia.atlassian.net/browse/GROWTH-738) to remove duplicate content, but maybe too many things were removed. @cannedyeti could you provide some information on this?

**Review by cannedyeti — APPROVED** [review]
Looks like this was a misunderstanding on my part. These should be indexable. The future SEO (to cdn.algorithmia.com) changes will fix the issues described in Growth-738.

**Comment by kennydaniel** [comment]
Yea i just found this commit:

https://github.com/algorithmiaio/dev-center/commit/589788cad23b2f98ea833617f4174e542b47e135

if its duplicates then I can see the case for it. Should make sure though because some pages like "local development" seem to have gotten lost.

**Pull request merged**
