### PR TITLE
Docker local dev

### PR DESCRIPTION
**Pull request by bnlb**
This PR updates local dev to work with docker compose, so that we're not constantly fighting issues with our individual computers.

💡 Opening as a draft since I want someone else to play around with it before I clean up some rough edges. Verified it works fine if I clone down a new repo and go through the steps in the updated readme.

```
❯ docker-compose up
Starting dev-center-test_slate_1  ... done
Starting dev-center-test_jekyll_1 ... done
Starting dev-center-test_node_1   ... done
Attaching to dev-center-test_slate_1, dev-center-test_jekyll_1, dev-center-test_node_1
node_1    | yarn run v1.22.5
node_1    | $ NODE_ENV=development yarn server
node_1    | $ node ./server/index.js
node_1    | {"name":"dev-center-server","hostname":"565817ca7556","pid":41,"level":30,"msg":"Starting server","time":"2021-03-23T18:29:55.905Z","v":0}
node_1    | [HPM] Proxy created: /  -> http://slate:4567
node_1    | [HPM] Proxy rewrite rule created: "^/developers/api/" ~> ""
node_1    | [HPM] Proxy created: /  -> http://jekyll:4001
node_1    | {"name":"dev-center-server","hostname":"565817ca7556","pid":41,"level":30,"msg":"Server started on port 4000.","time":"2021-03-23T18:29:55.966Z","v":0}
slate_1   | == The Middleman is loading
slate_1   | == Sprockets will render css with ruby sass
slate_1   |    consider using Sprockets 4.x to render with SassC
slate_1   | == View your site at "http://localhost:4567", "http://127.0.0.1:4567"
slate_1   | == Inspect your site configuration at "http://localhost:4567/__middleman", "http://127.0.0.1:4567/__middleman"
jekyll_1  | Configuration file: /jekyll/_config.yml
jekyll_1  | Configuration file: /jekyll/_config-dev.yml
jekyll_1  |             Source: /jekyll
jekyll_1  |        Destination: /jekyll/_site
jekyll_1  |  Incremental build: disabled. Enable with --incremental
jekyll_1  |       Generating...
jekyll_1  |                     done in 27.595 seconds.
jekyll_1  |  Auto-regeneration: enabled for '/jekyll'
jekyll_1  |     Server address: http://0.0.0.0:4001/developers/
jekyll_1  |   Server running... press ctrl-c to stop.
```

Screen Shot 2021-03-23 at 11 32 10 AM
Screen Shot 2021-03-23 at 11 32 26 AM

### CODE REVIEW

**Comment by lemonez** [comment]
doooope, looking forward to playing around with this when I get a chance, probably Friday.

**Comment by stevielkim** [comment]
I tried it out finally, and works perfectly, you rock @bnlb! The only thing that was easily noticeable was a typo "git submodule init && git submodule **udpate**" should be "update"

**Comment by bnlb** [comment]
> I tried it out finally, and works perfectly, you rock @bnlb! The only thing that was easily noticeable was a typo "git submodule init && git submodule **udpate**" should be "update"

Thanks so much for taking a look. I'll get this polished up a bit before opening a real PR and fix that typo.

**Comment by bnlb** [comment]
Temporarily closing. Will reopen once ready for prod.

**Pull request closed without merging**
